


export interface Paragraph {
    paragraph: string;
}


export interface Content {
    title: string;
    paragraphs: Paragraph[];
}


export interface TeamMember {
    name: string;
    title: string;
    quote?: string; 
    gallery: string[]; 
}


export interface Introduction {
    heading: string;
    paragraphs: Paragraph[];
}


export interface Mission {
    heading: string;
    title: string;
    content: Content[]; 
}

// Type for the blog post
export interface Blog {
    _id: string; // ID generated by Mongoose
    title: string;
    slug: string;
    introduction: Introduction;
    image: string[]; // Array of image URLs
    mission: Mission;
    team: TeamMember[];
    createdAt: string; // ISO date string
    updatedAt: string; // ISO date string
}
